# Generated by Django 3.0.5 on 2020-04-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('bid', models.DecimalField(decimal_places=5, max_digits=19)),
                ('ask', models.DecimalField(decimal_places=5, max_digits=19)),
                ('high', models.DecimalField(decimal_places=5, max_digits=19)),
                ('low', models.DecimalField(decimal_places=5, max_digits=19)),
            ],
            options={
                'unique_together': {('name', 'date')},
            },
        ),
    ]
