# Generated by Django 3.0.5 on 2020-04-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('script', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-date']},
        ),
    ]
