# Generated by Django 3.0.5 on 2020-04-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0002_auto_20200406_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='script',
            field=models.FileField(upload_to='uploads/models/'),
        ),
    ]
