# Generated by Django 3.0.5 on 2020-04-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0003_auto_20200406_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='accuracy',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='model',
            name='exec_time',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='model',
            name='mae',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='model',
            name='production',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='model',
            name='profit',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='model',
            name='r2',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='model',
            name='rmse',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='model',
            name='run',
            field=models.BooleanField(default=True),
        ),
    ]
