# Generated by Django 3.0.5 on 2020-04-06 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0004_auto_20200406_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
