# Generated by Django 3.0.5 on 2020-04-06 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0006_auto_20200406_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='run',
            new_name='run_model',
        ),
        migrations.RemoveField(
            model_name='model',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='model',
            name='exec_time',
        ),
        migrations.RemoveField(
            model_name='model',
            name='mae',
        ),
        migrations.RemoveField(
            model_name='model',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='model',
            name='r2',
        ),
        migrations.RemoveField(
            model_name='model',
            name='rmse',
        ),
    ]
