# Generated by Django 3.0.5 on 2020-04-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0008_run'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='run',
            name='modified_on',
        ),
        migrations.AlterField(
            model_name='run',
            name='accuracy',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='run',
            name='exec_time',
            field=models.DecimalField(decimal_places=5, max_digits=19),
        ),
        migrations.AlterField(
            model_name='run',
            name='mae',
            field=models.DecimalField(decimal_places=5, max_digits=19),
        ),
        migrations.AlterField(
            model_name='run',
            name='profit',
            field=models.DecimalField(decimal_places=5, max_digits=19),
        ),
        migrations.AlterField(
            model_name='run',
            name='r2',
            field=models.DecimalField(decimal_places=5, max_digits=19),
        ),
        migrations.AlterField(
            model_name='run',
            name='rmse',
            field=models.DecimalField(decimal_places=5, max_digits=19),
        ),
    ]
