# Generated by Django 3.0.5 on 2020-04-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0010_model_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='parameters',
        ),
        migrations.AddField(
            model_name='run',
            name='parameters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
