# Generated by Django 3.0.5 on 2020-04-07 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0011_auto_20200407_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='production',
        ),
        migrations.AddField(
            model_name='model',
            name='type',
            field=models.CharField(choices=[('T', 'Test'), ('P', 'Production')], default='T', max_length=1),
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.TextField(blank=True, null=True)),
                ('predictor', models.IntegerField()),
                ('value', models.FloatField()),
                ('exec_time', models.DecimalField(decimal_places=5, max_digits=19)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investing.Model')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='investing.Prediction')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
